@startuml Action Timing Diagram

title Action Timing Diagram

robust "Action Manager States" as actionManagerState
clock "Action Manager Tick" as actionManagerTick with period 100 pulse 5
clock "Player Tick" as player with period 100 pulse 5 offset 50
clock "Entities Tick" as entities with period 100 pulse 5 offset 75

@0
actionManagerState is Stopped

@150
actionManagerState is Starting

@200
actionManagerState is InProgress

@500
actionManagerState is Restarting

@600
actionManagerState is InProgress

@900
actionManagerState is Restarting

@950
actionManagerState is Stopping

@1000
actionManagerState is Stopped

@enduml
