
#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

name: Game Pipeline
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop  

jobs:
  build:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # - name: Setup .NET Core SDK 3.1
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: '3.1.x'

      # - name: Restore Dependencies
      #   run: dotnet restore

      # - name: Build
      #   run: dotnet build --no-restore

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal

      - name: Linting
        uses: mcr.microsoft.com/dotnet/sdk:6.0
        run: dotnet-format dungeon-crawler --verify-no-changes